---
name: Build release series tagged images

on:
  push:
    branches:
      - dockerxcache-testing
  #pull_request:
    #branches:
      #- '**'
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
  image-builds:
    name: xcache:${{ matrix.osg_series }}-${{ matrix.repo }} image build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        image: [atlas-xcache, cms-xcache, stash-cache, stash-origin]
        repo: ['development', 'testing', 'release']
        osg_series: ['3.6']
    steps:

      - uses: actions/checkout@v2

      - name: Build xcache base image
        uses: docker/build-push-action@v2.2.2
        with:
          context: ./xcache
          build-args: |
            BASE_YUM_REPO=${{ matrix.repo }}
            BASE_OSG_SERIES=${{ matrix.osg_series }}
          pull: True
          load: True
          tags: xcache:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Build xcache images
        uses: docker/build-push-action@v2.2.2
        with:
          context: ${{matrix.image}}
          build-args: |
            BASE_YUM_REPO=${{ matrix.repo }}
            BASE_OSG_SERIES=${{ matrix.osg_series }}
